### PR TITLE
Add store feature

### PR DESCRIPTION
**Pull request by loicgelle**
This PR adds the possibility to copy the generated bitcode files into a directory given by an environment variable. Details are in the changed readme file.

### CODE REVIEW

**Review by ianamason — COMMENTED** [review]
Any reason why you futzed with the DragoneggBuilder class?  I notice in all the travis builds the dragonegg tests fail now.

**Comment by loicgelle** [comment]
@ianamason It was accidental code removal. For the rest, there are still a few changes in the DragoneggBuilder class, because I don't consider that removing unused functions is futzing.

**Comment by ianamason** [comment]
Good, it builds without errors now.  Thanks for that Loic.

**Comment by loicgelle** [comment]
👍

**Pull request merged**
